# Generated by Django 5.2.7 on 2026-01-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue_booking', '0002_rename_status_booking_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
